name: Test Ephemeral CI

on:
  workflow_dispatch:

jobs:
  test-linux-r9700:
    runs-on: [self-hosted, Linux, r9700]
    steps:
      - run: echo "Hello from $(hostname) - $(uname -a)"

  test-linux-stx:
    runs-on: [self-hosted, Linux, stx]
    steps:
      - run: echo "Hello from $(hostname) - $(uname -a)"

  test-windows-stx:
    runs-on: [self-hosted, Windows, stx]
    steps:
      - run: Write-Output "Hello from $env:COMPUTERNAME"
